name = "HappyScheduler"
uuid = "9401c9d5-5572-4773-a0a4-219d48e60075"
authors = ["Kai FriebertshÃ¤user"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
